### ISSUE TITLE
Adding provider to Vapor project throws error

### ISSUE THREAD

**Issue by candostdagdeviren** [vapor/mongo-provider#15]
Hello,

I'm using Vapor 2 with MongoProvider. But the code below compiles but throws an error and prints the message inside the catch block.

```swift
do {
    try config.addProvider(MongoProvider.Provider.self)
} catch {
  print("Adding provider failed")
}
```

I have `fluent.json` file and it has the only uuid type declaration.

```json
{
   "idType": "uuid"
}
```

Lastly, I have `mongo.json` file under Config folder.

```json
{
  "host": "127.0.0.1",
  "database": "test_db",
  "port": "27017",
  "user": "admin",
  "password": "password"
}
```

Am I missing something or is there a bug?

**Comment by vzsg** [comment]
You should probably print the `error` itself in that catch block to see the actual error message.

**Comment by candostdagdeviren** [comment]
The error says `Configuration error: Key driver in Config/fluent.json of type String required.` What should I put to fluent.json?

**Comment by candostdagdeviren** [comment]
OK. I added `"driver": "mongo"` to my fluent.json file but, it seems setting the url in config became mandatory although I gave the host, database, port, user, password parameters separately.
